In [1]:
%pylab inline
from sklearn import datasets, linear_model, neighbors, model_selection, neural_network

Populating the interactive namespace from numpy and matplotlib


/home/mahinmy/桌面/ml_class/venv/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
data = datasets.load_iris()
X, y = data.data, data.target

In [8]:
for i in [3,5,10]:
    model1 = neighbors.KNeighborsClassifier(n_neighbors=5)
    print(model_selection.cross_val_score(model1, X, y, cv=5))

[0.96666667 1.         0.93333333 0.96666667 1.        ]
[0.96666667 1.         0.93333333 0.96666667 1.        ]
[0.96666667 1.         0.93333333 0.96666667 1.        ]


In [9]:
model2 = linear_model.LogisticRegression()
model_selection.cross_val_score(model2, X, y, cv=5)

/home/mahinmy/桌面/ml_class/venv/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/mahinmy/桌面/ml_class/venv/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/home/mahinmy/桌面/ml_class/venv/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/mahinmy/桌面/ml_class/venv/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/home/mahinmy/桌面/ml_class/venv/lib/python3

array([1.        , 0.96666667, 0.93333333, 0.9       , 1.        ])

In [11]:
model3 = neural_network.MLPClassifier(hidden_layer_sizes=(100,))
model_selection.cross_val_score(model3, X, y, cv=5)

/home/mahinmy/桌面/ml_class/venv/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/mahinmy/桌面/ml_class/venv/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/mahinmy/桌面/ml_class/venv/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/mahinmy/桌面/ml_class/venv/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and th

array([1.        , 1.        , 0.93333333, 0.9       , 1.        ])

In [12]:
model3 = neural_network.MLPClassifier(hidden_layer_sizes=(200,))
model_selection.cross_val_score(model3, X, y, cv=5)

/home/mahinmy/桌面/ml_class/venv/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/mahinmy/桌面/ml_class/venv/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/mahinmy/桌面/ml_class/venv/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/home/mahinmy/桌面/ml_class/venv/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:566: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and th

array([1.        , 1.        , 0.93333333, 0.93333333, 1.        ])